import { StyleSheet } from 'react-native';

export const createAuthStyles = ({ colors, shadow, isDark }) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 32,
      gap: 16,
    },
    topActions: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
      marginBottom: 4,
    },
    iconBtn: {
      width: 40,
      height: 40,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
    },
    hero: {
      borderRadius: 20,
      overflow: 'hidden',
      backgroundColor: '#0f172a',
      ...shadow,
    },
    heroInner: {
      padding: 22,
      gap: 10,
      backgroundColor: '#2563eb',
      position: 'relative',
    },
    heroKicker: {
      color: 'rgba(255,255,255,0.88)',
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 2,
      textTransform: 'uppercase',
    },
    heroTitle: {
      color: '#fff',
      fontSize: 26,
      fontWeight: '700',
      letterSpacing: -0.5,
      lineHeight: 32,
    },
    heroSubtitle: {
      color: 'rgba(255,255,255,0.88)',
      fontSize: 14,
      lineHeight: 22,
    },
    benefits: {
      marginTop: 8,
      gap: 10,
    },
    benefitRow: {
      alignItems: 'flex-start',
      gap: 10,
    },
    benefitIcon: {
      width: 40,
      height: 40,
      borderRadius: 14,
      backgroundColor: 'rgba(255,255,255,0.14)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    benefitCopy: {
      flex: 1,
      gap: 2,
    },
    benefitLabel: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '600',
    },
    benefitDesc: {
      color: 'rgba(255,255,255,0.82)',
      fontSize: 13,
      lineHeight: 18,
    },
    panel: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 19,
      padding: 22,
      gap: 16,
      ...shadow,
    },
    panelKicker: {
      color: colors.primary,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 2,
      textTransform: 'uppercase',
    },
    panelTitle: {
      color: colors.text,
      fontSize: 24,
      fontWeight: '700',
      letterSpacing: -0.4,
      lineHeight: 30,
      marginTop: 4,
    },
    panelSubtitle: {
      color: colors.muted,
      fontSize: 14,
      lineHeight: 21,
      marginTop: 4,
    },
    form: {
      gap: 14,
    },
    field: {
      gap: 8,
    },
    fieldRow: {
      gap: 12,
    },
    fieldHalf: {
      flex: 1,
      gap: 8,
    },
    label: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '600',
    },
    labelRow: {
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    required: {
      color: colors.danger,
    },
    input: {
      minHeight: 46,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      backgroundColor: isDark ? colors.surfaceAlt : colors.surfaceAlt,
      color: colors.text,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
    },
    inputError: {
      borderColor: colors.danger,
    },
    passwordWrap: {
      position: 'relative',
    },
    passwordInput: {
      paddingRight: 44,
    },
    passwordInputRtl: {
      paddingRight: 14,
      paddingLeft: 44,
    },
    passwordToggle: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      right: 12,
      justifyContent: 'center',
      paddingHorizontal: 4,
    },
    passwordToggleRtl: {
      right: undefined,
      left: 12,
    },
    errorText: {
      color: colors.danger,
      fontSize: 12,
      lineHeight: 17,
    },
    strengthTrack: {
      height: 4,
      borderRadius: 999,
      backgroundColor: colors.border,
      overflow: 'hidden',
    },
    strengthFill: {
      height: '100%',
      backgroundColor: colors.success,
    },
    checkboxRow: {
      alignItems: 'center',
      gap: 10,
    },
    checkboxBox: {
      width: 18,
      height: 18,
      borderRadius: 4,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surfaceAlt,
    },
    checkboxBoxChecked: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    checkboxLabel: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '500',
      flex: 1,
    },
    primaryBtn: {
      minHeight: 46,
      borderRadius: 999,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
      ...shadow,
    },
    primaryBtnText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '700',
    },
    dividerRow: {
      alignItems: 'center',
      gap: 10,
    },
    dividerLine: {
      flex: 1,
      height: 1,
      backgroundColor: colors.border,
    },
    dividerText: {
      color: colors.muted,
      fontSize: 13,
      fontWeight: '600',
    },
    googleBtn: {
      minHeight: 46,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: isDark ? colors.surfaceAlt : colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 10,
    },
    googleBtnText: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    inlineLink: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: '600',
    },
    footerSwitch: {
      textAlign: 'center',
      color: colors.muted,
      fontSize: 14,
      lineHeight: 22,
    },
    footerLink: {
      color: colors.primary,
      fontWeight: '700',
    },
  });
